NumPy (Numerical Python)

In [1]:
import numpy as np

myArray = np.array([2,4,6,8,10])
print(myArray)

[ 2  4  6  8 10]


In [5]:
import numpy as np
fruits = ["mango","banana","apple",450]
myArray = np.array(fruits)
print(fruits)
print(type(myArray))

['mango', 'banana', 'apple', 450]
<class 'numpy.ndarray'>


1-Dimension Array

In [7]:
import numpy as np

myArray = np.array([1,2,3,4,5])
dimension = myArray.ndim
print(dimension)

[1 2 3 4 5]
1


2-Dimensions Array

In [9]:
import numpy as np

myArray = np.array([[1,2,3,4,5],[6,7,8,9,0]])
dimension = myArray.ndim
print(dimension)

2


3-Dimensions Array

In [11]:
import numpy as np

myArray = np.array([[[1,2,3,4,5],[1,2,3,4,5],[6,7,8,9,0]]])
dimension = myArray.ndim
print(dimension)

3


Accessing array elements through indexing

In [16]:
import numpy as np

myArray = np.array([1,2,3,4,5])
print(myArray[2])

3


Array Slicing

In [19]:
import numpy as np

myArray = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(myArray[1,2:2])

[]


Array Iteration

In [21]:
import numpy as np

myArray = np.array([
    [
        [1,2,3,4,5],
         [1,2,3,4,5],
          [6,7,8,9,0]
        ]
    ])
for i in myArray:
 print(myArray)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [6 7 8 9 0]]]


Array Concatenation

In [23]:
import numpy as np

myArray = np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,0])
con = np.concatenate((myArray,array2))
print(con)

[1 2 3 4 5 6 7 8 9 0]


Splitting Array

In [24]:
import numpy as np

myArray = np.array([[[1,2,3,4,5],[1,2,3,4,5],[6,7,8,9,0]]])
splitarr = np.array_split(myArray,3)
print(splitarr[0])

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [6 7 8 9 0]]]


Searching Array

In [25]:
import numpy as np

myArray = np.array([[[1,2,3,4,5],[1,2,3,4,5],[6,7,8,9,0]]])
x = np.where(myArray == 6)
print(x)

(array([0]), array([2]), array([0]))


Array search sorting

In [27]:
import numpy as np

myArray = np.array([1,2,3,4,5])
x = np.searchsorted(myArray, 6)
print(x)

5


Lab Task
-------
Creating a 3x3 matrix with values ranging from 2 to 10, convert array to a float type. Write a Python program to find the maximum and minimum value of flattened array.

In [38]:
import numpy as np

myArray = np.array([
    [
        [2,4,6,8,10],
         [3,4,5,6,7],
          [6,7,8,9,5]
        ]
    ])
array_type = myArray.astype(float)  # changing array type into float
print("array in float type\n")
print(array_type)

# Flatten the array
flatenedArray = myArray.flatten()

# Find maximum and minimum
max_value = np.max(flatenedArray)
min_value = np.min(flatenedArray)

print("Flattened Array:", myArray)
print("Maximum Value:", max_value)
print("Minimum Value:", min_value)



array in float type

[[[ 2.  4.  6.  8. 10.]
  [ 3.  4.  5.  6.  7.]
  [ 6.  7.  8.  9.  5.]]]
Flattened Array: [[[ 2  4  6  8 10]
  [ 3  4  5  6  7]
  [ 6  7  8  9  5]]]
Maximum Value: 10
Minimum Value: 2
